include("${MPI_CONFIG}")
file(READ "${INPUT}" original)
foreach(case_name lowq operator geometry cfl fault buffer resolution incompatible mechanisms coefficient fitlimit)
  set(text "${original}")
  if(case_name STREQUAL lowq)
    string(REPLACE "Qs0=400d0,800d0" "Qs0=200d0,800d0" text "${text}")
    set(expected CFG-CGT-004)
  elseif(case_name STREQUAL operator)
    string(REPLACE "order=6" "order=4" text "${text}")
    set(expected CFG-CGT-003)
  elseif(case_name STREQUAL geometry)
    string(REPLACE "use_topography=F" "use_topography=T" text "${text}")
    set(expected CFG-CGT-002)
  elseif(case_name STREQUAL cfl)
    string(REPLACE "CFL=0.25d0" "CFL=0.5d0" text "${text}")
    set(expected CFG-CGT-006)
  elseif(case_name STREQUAL fault)
    string(REPLACE "coupling='locked'" "coupling='slip-weakening_friction'" text "${text}")
    set(expected CFG-CGT-005)
  elseif(case_name STREQUAL buffer)
    string(REPLACE "boundary_policy='full-buffer'" "boundary_policy='full-buffer', buffer_layers=30" text "${text}")
    set(expected "no complete projected interior cell")
  elseif(case_name STREQUAL resolution)
    string(REPLACE "fmax=5d0" "fmax=10d0" text "${text}")
    set(expected "24.1 points per shortest S wavelength")
  elseif(case_name STREQUAL mechanisms)
    string(REPLACE "boundary_policy='full-buffer'" "boundary_policy='full-buffer', n_mechanisms=4" text "${text}")
    set(expected CFG-CGT-001)
  elseif(case_name STREQUAL coefficient)
    string(REPLACE "additive-passive-fit" "constrained-effective-fit" text "${text}")
    set(expected CFG-CGT-001)
  elseif(case_name STREQUAL fitlimit)
    string(REPLACE "max_fit_error=0.01d0" "max_fit_error=0.03d0" text "${text}")
    set(expected CFG-CGT-001)
  else()
    string(REPLACE "Qp0=600d0,1000d0" "Qp0=4000d0,1000d0" text "${text}")
    set(expected "incompatible P/S targets")
  endif()
  set(case_input "${CMAKE_CURRENT_BINARY_DIR}/cgt_invalid_${case_name}.in")
  file(WRITE "${case_input}" "${text}")
  execute_process(COMMAND "${MPIEXEC}" ${MPIEXEC_NUMPROC_FLAG} 1 ${MPIEXEC_PREFLAGS}
    "${EXE}" ${MPIEXEC_POSTFLAGS} "${case_input}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(result STREQUAL "0" OR NOT "${output}${error}" MATCHES "${expected}")
    message(FATAL_ERROR "CGT invalid case ${case_name} expected ${expected}, got ${result}: ${output}\n${error}")
  endif()
endforeach()
