include("${MPI_CONFIG}")
file(READ "${INPUT}" original)
foreach(case_name lowq operator centered6 drp4 geometry cfl fault buffer resolution incompatible)
  set(text "${original}")
  if(case_name STREQUAL lowq)
    string(REPLACE "Qs0=400d0,800d0" "Qs0=200d0,800d0" text "${text}")
    set(expected CFG-CG8-004)
  elseif(case_name STREQUAL operator)
    string(REPLACE "fd_type='upwind'" "fd_type='traditional'" text "${text}")
    set(expected CFG-CG8-003)
  elseif(case_name STREQUAL centered6)
    string(REPLACE "fd_type='upwind', order=4" "fd_type='traditional', order=6" text "${text}")
    set(expected CFG-CG8-003)
  elseif(case_name STREQUAL drp4)
    string(REPLACE "fd_type='upwind'" "fd_type='upwind_drp'" text "${text}")
    set(expected CFG-CG8-003)
  elseif(case_name STREQUAL geometry)
    string(REPLACE "use_topography=F" "use_topography=T" text "${text}")
    set(expected CFG-CG8-002)
  elseif(case_name STREQUAL cfl)
    string(REPLACE "CFL=0.25d0" "CFL=0.5d0" text "${text}")
    set(expected CFG-CG8-006)
  elseif(case_name STREQUAL fault)
    string(REPLACE "coupling='locked'" "coupling='slip-weakening_friction'" text "${text}")
    set(expected CFG-CG8-005)
  elseif(case_name STREQUAL buffer)
    string(REPLACE "boundary_policy='full-buffer'" "boundary_policy='full-buffer', buffer_layers=30" text "${text}")
    set(expected "no complete coarse interior cell")
  elseif(case_name STREQUAL resolution)
    string(REPLACE "0.4d0" "4d0" text "${text}")
    set(expected "16.1 points per shortest S wavelength")
  else()
    string(REPLACE "Qp0=600d0,1000d0" "Qp0=4000d0,1000d0" text "${text}")
    set(expected "incompatible P/S targets")
  endif()
  set(case_input "${CMAKE_CURRENT_BINARY_DIR}/cg8_invalid_${case_name}.in")
  file(WRITE "${case_input}" "${text}")
  execute_process(COMMAND "${MPIEXEC}" ${MPIEXEC_NUMPROC_FLAG} 1 ${MPIEXEC_PREFLAGS}
    "${EXE}" ${MPIEXEC_POSTFLAGS} "${case_input}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(result STREQUAL "0" OR NOT "${output}${error}" MATCHES "${expected}")
    message(FATAL_ERROR "CG8 invalid case ${case_name} expected ${expected}, got ${result}: ${output}\n${error}")
  endif()
endforeach()
