include("${MPI_CONFIG}")
file(READ "${INPUT}" input_text)
foreach(n RANGE 4 8)
  string(REPLACE "n_mechanisms=8" "n_mechanisms=${n}" case_text "${input_text}")
  set(case_input "${CMAKE_CURRENT_BINARY_DIR}/test_anelastic_fQ_n${n}.in")
  # Four mechanisms need a looser bound over this broad transition band.
  string(REPLACE "max_fit_error=0.10d0" "max_fit_error=0.30d0" case_text "${case_text}")
  file(WRITE "${case_input}" "${case_text}")
  execute_process(COMMAND "${MPIEXEC}" ${MPIEXEC_NUMPROC_FLAG} 1 ${MPIEXEC_PREFLAGS} "${EXE}" ${MPIEXEC_POSTFLAGS} "${case_input}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "anelastic-fQ N=${n} failed: ${error}\n${output}")
  endif()
  string(FIND "${output}" "anelastic-fQ mechanisms: ${n}" count_position)
  string(REGEX MATCH "fQ final state: max\\|field\\|=[^\n]+" state "${output}")
  if(count_position EQUAL -1 OR state STREQUAL "")
    message(FATAL_ERROR "anelastic-fQ N=${n} diagnostics are missing")
  endif()
  if(state MATCHES "max\\|memory\\|= *0\\.0+E\\+00")
    message(FATAL_ERROR "anelastic-fQ N=${n} did not evolve memory variables")
  endif()
endforeach()
