include("${MPI_CONFIG}")
file(READ "${INPUT}" original)
foreach(case_name n3 n9 one_block gamma q_nonpositive q_low transition band reference policy samples tolerance table4 partial)
  set(text "${original}")
  set(code CFG-FQ-001)
  if(case_name STREQUAL n3)
    string(REPLACE "n_mechanisms=8" "n_mechanisms=3" text "${text}")
  elseif(case_name STREQUAL n9)
    string(REPLACE "n_mechanisms=8" "n_mechanisms=9" text "${text}")
  elseif(case_name STREQUAL one_block)
    string(REPLACE "nblocks=2" "nblocks=1" text "${text}")
    string(REPLACE "btp(1)%rqrs=0,1,1" "btp(1)%rqrs=1,1,1" text "${text}")
    set(code CFG-FQ-002)
  elseif(case_name STREQUAL gamma)
    string(REPLACE "gamma=0.6d0" "gamma=1d0" text "${text}")
  elseif(case_name STREQUAL q_nonpositive)
    string(REPLACE "Qs0=40d0,120d0" "Qs0=0d0,120d0" text "${text}")
  elseif(case_name STREQUAL q_low)
    string(REPLACE "Qs0=40d0,120d0" "Qs0=14d0,120d0" text "${text}")
  elseif(case_name STREQUAL transition)
    string(REPLACE "f_transition=1d0" "f_transition=0d0" text "${text}")
  elseif(case_name STREQUAL band)
    string(REPLACE "fmin=0.05d0" "fmin=30d0" text "${text}")
  elseif(case_name STREQUAL reference)
    string(REPLACE "fref=1d0" "fref=30d0" text "${text}")
  elseif(case_name STREQUAL policy)
    string(REPLACE "nnls-block-ps" "nnls-shared" text "${text}")
  elseif(case_name STREQUAL samples)
    string(REPLACE "nnls_samples=256" "nnls_samples=2" text "${text}")
  elseif(case_name STREQUAL tolerance)
    string(REPLACE "nnls_tolerance=1d-10" "nnls_tolerance=0d0" text "${text}")
  elseif(case_name STREQUAL table4)
    string(REPLACE "n_mechanisms=8" "n_mechanisms=4, relaxation_policy='fq8-table'" text "${text}")
  else()
    string(REPLACE "Qs0=40d0,120d0" "Qs0(1)=40d0" text "${text}")
  endif()
  set(case_input "${CMAKE_CURRENT_BINARY_DIR}/fq_invalid_${case_name}.in")
  file(WRITE "${case_input}" "${text}")
  execute_process(COMMAND "${MPIEXEC}" ${MPIEXEC_NUMPROC_FLAG} 1 ${MPIEXEC_PREFLAGS}
    "${EXE}" ${MPIEXEC_POSTFLAGS} "${case_input}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(result STREQUAL "0" OR NOT "${output}${error}" MATCHES "${code}")
    message(FATAL_ERROR "fQ invalid case ${case_name}: expected ${code}; got ${result}\n${output}\n${error}")
  endif()
endforeach()
