include("${MPI_CONFIG}")
foreach(ranks 1 8)
  execute_process(COMMAND "${MPIEXEC}" ${MPIEXEC_NUMPROC_FLAG} ${ranks} ${MPIEXEC_PREFLAGS}
    "${EXE}" ${MPIEXEC_POSTFLAGS} "${INPUT}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "CG-T ${ranks}-rank one-block run failed: ${error}\n${output}")
  endif()
  string(REGEX MATCH "CG-T final state: max\\|field\\|=[^\n]+" current "${output}")
  if(current STREQUAL "" OR current MATCHES "max\\|field\\|= *0\\.0+E\\+00" OR current MATCHES "max\\|memory\\|= *0\\.0+E\\+00")
    message(FATAL_ERROR "CG-T one-block run did not evolve memory: ${output}")
  endif()
  if(ranks EQUAL 1)
    set(reference "${current}")
  else()
    if(NOT output MATCHES "topology 2 2 2" OR NOT output MATCHES "max cell peers=7")
      message(FATAL_ERROR "CG-T solver test did not exercise corner routes: ${output}")
    endif()
    if(NOT current STREQUAL reference)
      message(FATAL_ERROR "CG-T one/eight-rank final-state mismatch: ${reference}\n${current}")
    endif()
  endif()
endforeach()
